#!/usr/bin/env ruby

# -------------------------------------------------------------------------- #
# Copyright 2002-2026, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #
ONE_LOCATION = ENV['ONE_LOCATION']

if !ONE_LOCATION
    RUBY_LIB_LOCATION = '/usr/lib/one/ruby'
    GEMS_LOCATION     = '/usr/share/one/gems'
    VMDIR             = '/var/lib/one'
    CONFIG_FILE       = '/var/lib/one/config'
else
    RUBY_LIB_LOCATION = ONE_LOCATION + '/lib/ruby'
    GEMS_LOCATION     = ONE_LOCATION + '/share/gems'
    VMDIR             = ONE_LOCATION + '/var'
    CONFIG_FILE       = ONE_LOCATION + '/var/config'
end

# %%RUBYGEMS_SETUP_BEGIN%%
require 'load_opennebula_paths'
# %%RUBYGEMS_SETUP_END%%

$LOAD_PATH << RUBY_LIB_LOCATION

VERSION_FILE = File.join File.dirname(__FILE__), '..', '..', 'VERSION'

require 'base64'
require 'opennebula'
require 'rexml/document'

require 'CommandManager'
require 'HostSyncManager'
require_relative 'restic'

daction64 = STDIN.read
ds_id = ARGV[0]

begin
    action = Base64.decode64 daction64

    rds = Restic.new action, :prefix => 'DATASTORE/'
    stats = rds.monitor_stats(:ds_id        => ds_id,
                              :version_file => VERSION_FILE)
rescue StandardError => e
    STDERR.puts e.full_message
    exit(-1)
end

STDOUT.puts "USED_MB=#{stats[:used_mb]}"
STDOUT.puts "TOTAL_MB=#{stats[:total_mb]}"
STDOUT.puts "FREE_MB=#{stats[:free_mb]}"

exit(0)
